config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :medicinas
  resources :meetings
  resources :events
  resources :personas

  root to: 'personas#index'

  resources :personas do
  resources :medicinas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.order ('start_time DESC')
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="row">
  <div class="small-5 large-12 columns">
  <div class="field">
    <%= form.label :nombre_del_padre %>
    <%= form.text_field :name, id: :meeting_name %>
  </div>
 <div class="field">
    <%= form.label :Hora_y_fecha_de_la_cita %>
    <%= form.datetime_select :start_time, {:ampm => true} %>
  </div>

  <div class="actions">
    <%= form.submit  ( form.object.new_record? ? "Crear" : "Actualizar"), class: "button secondary" %>
  </div>
   </div></div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, @meeting %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, meetings_path %>|
<%= link_to '<button type="button" class="button warning basci">Inicio</button>'.html_safe, meetings_path %>

</center>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table WITH="99%">
  <thead>
    <tr>
      <th>nombre del padre</th>
      <th>Día de la cita</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time.strftime("%d %B, %Y, %I:%M")  %></td>
        <td><%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, meeting %></td>
        <% if current_user.role == "Doctor" %>
        <td><%= link_to '<button type="button" class="button success small">Editar</button>'.html_safe, edit_meeting_path(meeting) %></td>
        <td><%= link_to '<button type="button" class="button alert small">Eliminar!</button>'.html_safe, meeting, method: :delete, data: { confirm: '¿Estas seguro?' } %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.role == "Doctor" %>
<%= link_to '<button type="button" class="button warning basci">Agendar cita</button>'.html_safe, new_meeting_path %>
<% end %>
</center>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, meetings_path %>
</center>

app/views/meetings/show.html.erb
<div class="row">
  <div class="large-12 columns imagen">
  <center>

<p>
  <strong>Nombre del padre:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Hora y fecha de la cita:</strong>
  <%= @meeting.start_time.strftime("%d %B, %Y, %I:%M") %>
</p>

<% if current_user.role == "Doctor" %>
<%= link_to '<button type="button" class="button success basic">Editar</button>'.html_safe, edit_meeting_path(@meeting) %> |
<% end %>
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, meetings_path %>

</div></div>
</center>