config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :medicinas
  resources :meetings
  resources :events
  resources :personas

  root to: 'personas#index'

  resources :personas do
  resources :medicinas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/persona.rb
class Persona < ApplicationRecord
   has_many :medicinas
    
    mount_uploader :foto, FotoUploader
    validates :contacto, length: {maximum: 10}
    validates :edad,  numericality: {only_integer: true, message: "Sólo números!!"}
    validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
    validates :direccion, :descripcion, :peso, :altura, :padre, presence: true

def self.search(search)
  where("nombre LIKE ? OR edad LIKE ? OR padre LIKE ? OR descripcion LIKE ?
   OR peso LIKE ? OR altura LIKE ? ",
  "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%" ) 
end
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: [:show, :edit, :update, :destroy]

  # GET /personas
  # GET /personas.json
  def index
    @personas = Persona.order(:padre)
    if params[:search]
      @personas = Persona.search(params[:search]).order(:padre)
    else
      @personas = Persona.all.order(:padre)
    end
  end

class PersonaPdf < Prawn::Document
    def initialize(persona)
        super(top_margin: 70, left_margin: 50, right_margin: 50)
        @persona = persona
        persona_id
        
    end

    def persona_id
      pdf = Prawn::Document.new
      text "paciente #{@persona.nombre}", size:30, style: :bold
      text ("")
      text "____________________________________________________________________________", size: 12
      text "\n"
      text "Edad: ", size: 14, style: :bold
      text "#{@persona.edad}", size: 12
      text "\n"
      text "Descripción: ", size: 14, style: :bold
      text "#{@persona.descripcion}", size: 12
      text "\n"
      text "Peso: ", size: 14, style: :bold
      text "#{@persona.peso}", size: 12
      text "\n"
      text "Altura: ", size: 14, style: :bold
      text "#{@persona.altura}", size: 12
      text "\n"
      text "Padre: ", size: 14, style: :bold
      text "#{@persona.padre}", size: 12
      text "\n"
      text "Dirrección: ", size: 14, style: :bold
      text "#{@persona.direccion}", size: 12
      text "\n"
      text "Telefono: ", size: 14, style: :bold
      text "#{@persona.contacto}", size: 12
      end    
end
  # GET /personas/1
  # GET /personas/1.json
  def show
    @persona = Persona.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PersonaPdf.new(@persona)
        send_data pdf.render, filename: "persona_#{@persona.nombre}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
        end
      end
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas
  # POST /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to @persona, notice: 'el paciente fue creada con exito.' }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1
  # PATCH/PUT /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to @persona, notice: 'el paciente fue editado con exito' }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.json
  def destroy
    @persona.destroy
    respond_to do |format|
      format.html { redirect_to personas_url, notice: 'el paciente fue eliminado con exito ' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def persona_params
      params.require(:persona).permit(:nombre, :edad, :padre, :descripcion, :peso, :altura, :foto, :direccion, :email, :contacto)
    end
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/personas/_form.html.erb
<%= form_with(model: persona, local: true) do |form| %>
  <% if persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% persona.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :persona_nombre %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :edad %>
    <%= form.number_field :edad, id: :persona_edad %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :persona_descripcion %>
  </div>
  </div>
 </div>
 <div class="row"> 
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :peso %>
    <%= form.text_field :peso, id: :persona_peso %>
  </div>
  </div>
   <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :altura %>
    <%= form.text_field :altura, id: :persona_altura %>
  </div>
  </div>
   <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :foto %>
    <%= form.file_field :foto, id: :persona_foto %>
  </div>
  </div>
  </div>
  <h1> Datos de padre </h1>
  <div class="row">
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :nombre del padre %>
    <%= form.text_field :padre, id: :persona_padre %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :persona_direccion %>
  </div>
  </div>
  </div>
  <div class="row">
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :persona_email %>
  </div>
  </div>
  <div class="small-5 large-4 columns">
  <div class="field">
    <%= form.label :contacto %>
    <%= form.text_field :contacto, id: :persona_contacto %>
  </div>
 </div>
  </div>
  <div class="actions">
    <%= form.submit ( form.object.new_record? ? "Crear" : "Actualizar"), class: "button secondary" %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing Persona</h1>

<%= render 'form', persona: @persona %>

<%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, @persona %> |
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, persona_path %>|
<%= link_to '<button type="button" class="button warning basci">Inicio</button>'.html_safe, persona_path %>

app/views/personas/index.html.erb
<style>
img{
  max-width:  300%;
}
td{
  width: 40px;
}

table{
  vertical-align: center;
}
</style>
<center>
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>
<% if !@personas.blank? %>
<table WIDTH="99%">
  <thead>
    <tr>
     <th colspan="2">Foto</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Padre</th>
      <th>Descripcion</th>
      <th>Peso</th>
      <th>Altura</th>
      <th>Direccion</th>
      <th>Email</th>
      <th>Contacto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personas.each do |persona| %>
      <tr>
      <td><%= image_tag(persona.foto_url)if persona.foto? %></td>
        <td></td>
        <td><%= persona.nombre %></td>
        <td><%= persona.edad %></td>
        <td><%= persona.padre %></td>
        <td><%= persona.descripcion %></td>
        <td><%= persona.peso %></td>
        <td><%= persona.altura %></td>
        <td><%= persona.direccion %></td>
        <td><%= persona.email %></td>
        <td><%= persona.contacto %></td>
        <td><%= link_to '<button type="button" class="button primary small">Mostrar</button>'.html_safe, persona %></td>
        <% if current_user.role == "Doctor" %>
        <td><%= link_to '<button type="button" class="button success small">Editar</button>'.html_safe, edit_persona_path(persona) %></td>
        <td><%= link_to '<button type="button" class="button alert small">¡Eliminar!</button>'.html_safe, persona, method: :delete, data: { confirm: '¿Estas seguro?' } %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% else %>
<div data-alert class="alert-box alert round large-5 small-7">
    No se encontró nada con <b>" <%= params[:search] %> "</b>
    <a href="#" class="close">&times;</a>
</div>

  <%= link_to '<button type="button" class="button">Inicio</button>'.html_safe, personas_path %>
<% end %>

<%= link_to '<button type="button" class="button warning basci">Nuevo paciente</button>'.html_safe, new_persona_path %>
</center>

app/views/personas/new.html.erb
<h1>Nuevo paciente</h1>

<%= render 'form', persona: @persona %>

<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, personas_path %>
</center>

app/views/personas/personaBus.html.erb
 <% @personasBus = Persona.where(@palabraB) %>
  
<table WIDTH="99%">
  <thead>
    <tr>
    <th colspan="2">Foto</th>
      <th>Nombre</th>
      <th>Edad</th>
      <th>Padre</th>
      <th>Descripción</th>
      <th>Peso</th>
      <th>Altura</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  </table>

app/views/personas/show.html.erb
<style>
img{
  max-width:  100%;
}
.imagen{
  width: 400px;
}
</style>
<%= link_to '<button type="button" class="button tiny success" id="open-hide">Generar PDF</button>'.html_safe, persona_path(@persona, format: "pdf") %> 

<div class="row">
<div class="large-8 columns imagen">
  <%= image_tag(@persona.foto_url) if @persona.foto?%>
  </div>
<div class="large-4 columns">
<p>
  <strong>Nombre:</strong>
  <%= @persona.nombre %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @persona.edad %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @persona.descripcion %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @persona.peso %>
</p>

<p>
  <strong>Altura:</strong>
  <%= @persona.altura %>
</p>

<p>
  <strong>Padre:</strong>
  <%= @persona.padre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @persona.direccion %>
</p>

<p>
  <strong>Email:</strong>
  <%= @persona.email %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @persona.contacto %>
</p>
</div>
</div>

<center>
<% if current_user.role == "Doctor" %>
<%= link_to '<button type="button" class="button success basic">Editar</button>'.html_safe, edit_persona_path(@persona) %> |
<% end %>
<%= link_to '<button type="button" class="button secondary basic">Regresar</button>'.html_safe, personas_path %>

<div class="row">
<% if current_user.role == "Doctor" %>
  <div class="large-2 columns">
  <% else %>
  <div class="large-12 colums">
  <% end %> 
  <h2>Medicinas</h2>
<% @persona.medicinas.each do |medicina| %>
   <p>
    <strong>Nombre:</strong>
    <%= medicina.nombre %>
  </p>
  <p>
    <strong>Aplicación:</strong>
    <%= medicina.aplicacion %>
  </p>
   <p>
    <strong>Descripcion:</strong>
    <%= medicina.descripcion %>
  </p>
  <p>
    <strong>Fecha:</strong>
    <%= medicina.fecha %>
  </p>
 <% end %>
  </div>

  <% if current_user.role == "Doctor" %>
<div class="large-6 columns">
<h2>Añadir medicamento</h2>
<%= form_for([@persona, @persona.medicinas.build]) do |form| %>
  <p>
    <%= form.label :nombre_del_medicamento %><br>
    <%= form.text_field :nombre %>
  </p>
  <p>
    <%= form.label :aplicación %><br>
    <%= form.select :aplicacion, ['Oral', 'Intradérmica', 'Subcutánea', 'Intramuscular'] %>
  </p>
   <p>
    <%= form.label :descripcion %><br>
    <%= form.text_area :descripcion %>
  </p>
  <p>
    <%= form.label :fecha %><br>
    <%= form.date_select :fecha %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
<% end %>
</div> </div>
</center>