config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
  get '/users/sign_out' => 'devise/sessions#destroy'
end
  resources :medicinas
  resources :meetings
  resources :events
  resources :personas

  root to: 'personas#index'

  resources :personas do
  resources :medicinas
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Pediatra" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
<script type="text/javascript">
function hola(){
  var palabraB = document.getElementById("queBus").value;
  location.href="personaBus.html";
 }
</script>

  <body>
<h3>P E D I A T R A </h3>
  <% if user_signed_in? %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">  
    <h1><%= link_to "Inicio", personas_path %></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right menu">          
      <li class="has-dropdown active">
        <a>Bienvenido <%= current_user.email %></a>
        <ul class="dropdown">
          <li><%= link_to "Editar perfil", edit_user_registration_path %></li>
          <li class="active"><%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    </ul>
  

    <% if current_user.role == "Doctor" %>
    <ul class="left">
      <li><%= link_to "Nuevo paciente", new_persona_path %></li>
    </ul>
    <ul class="left">
      <li><%= link_to "Nueva cita", new_meeting_path %></li>
    </ul>
    <ul class="left">
      <li><%= link_to "Citas", meetings_path %></li>
    </ul>
    <% else %>
    <ul class="left">
      <li><%= link_to "Citas", meetings_path %></li>
    </ul>
    <% end %>
  </section>
</nav>

<% else %>
<nav class="top-bar" data-topbar role="navigation">
  <section class="top-bar-section">
    <ul class="right menu">

              
  <li class="has-dropdown active">
  <a>Bienvenido(a)</a>
        <ul class="dropdown">
        <li class="active"><%= link_to "Usuario", new_user_session_path %></li>
        <li><%= link_to "Registro Usuario", new_user_registration_path %></li>
        </ul>
      </li>
    </ul>
    
  </section>
</nav>
<% end %>
    <%= yield %>
    <% if notice %> 
	<p class="alert alert-success"><%= notice %></p> <% end %> 
<% if alert %> 
	<p class="alert alert-danger"><%= alert %></p> 
<% end %>

    <%= javascript_include_tag "application" %>

  </body>
</html>